
export type City = {
    name: string;
};

export type Country = {
    name: string;
    cities: City[];
};

export const aseanCountries: Country[] = [
    {
        name: 'Brunei',
        cities: [
            { name: 'Bandar Seri Begawan' },
            { name: 'Kuala Belait' },
            { name: 'Seria' },
            { name: 'Tutong' },
            { name: 'Muara' },
            { name: 'Bangar' },
            { name: 'Jerudong' },
        ],
    },
    {
        name: 'Kamboja',
        cities: [
            { name: 'Phnom Penh' },
            { name: 'Siem Reap' },
            { name: 'Sihanoukville' },
            { name: 'Battambang' },
            { name: 'Kampot' },
            { name: 'Kep' },
            { name: 'Kampong Cham' },
            { name: 'Kampong Thom' },
            { name: 'Koh Kong' },
            { name: 'Kratié' },
            { name: 'Mondulkiri' },
            { name: 'Ratanakiri' },
            { name: 'Pursat' },
            { name: 'Prey Veng' },
            { name: 'Svay Rieng' },
            { name: 'Banteay Meanchey' },
            { name: 'Pailin' },
        ],
    },
    {
        name: 'Indonesia',
        cities: [
            { name: 'Aceh' },
            { name: 'Bali' },
            { name: 'Bangka Belitung' },
            { name: 'Banten' },
            { name: 'Bengkulu' },
            { name: 'DI Yogyakarta' },
            { name: 'DKI Jakarta' },
            { name: 'Flores' },
            { name: 'Gayo' },
            { name: 'Gorontalo' },
            { name: 'Ijen' },
            { name: 'Jambi' },
            { name: 'Jawa Barat' },
            { name: 'Jawa Tengah' },
            { name: 'Jawa Timur' },
            { name: 'Kalimantan Barat' },
            { name: 'Kalimantan Selatan' },
            { name: 'Kalimantan Tengah' },
            { name: 'Kalimantan Timur' },
            { name: 'Kalimantan Utara' },
            { name: 'Kepulauan Riau' },
            { name: 'Kintamani' },
            { name: 'Lampung' },
            { name: 'Lintong' },
            { name: 'Lombok' },
            { name: 'Maluku' },
            { name: 'Maluku Utara' },
            { name: 'Mandailing' },
            { name: 'Nusa Tenggara Barat' },
            { name: 'Nusa Tenggara Timur' },
            { name: 'Papua' },
            { name: 'Papua Barat' },
            { name: 'Riau' },
            { name: 'Sulawesi Barat' },
            { name: 'Sulawesi Selatan' },
            { name: 'Sulawesi Tengah' },
            { name: 'Sulawesi Tenggara' },
            { name: 'Sulawesi Utara' },
            { name: 'Sumatera Barat' },
            { name: 'Sumatera Selatan' },
            { name: 'Sumatera Utara' },
            { name: 'Sumbawa' },
            { name: 'Toraja' },
        ],
    },
    {
        name: 'Laos',
        cities: [
            { name: 'Vientiane' },
            { name: 'Luang Prabang' },
            { name: 'Pakse' },
            { name: 'Savannakhet' },
            { name: 'Bolaven Plateau' },
            { name: 'Phongsaly' },
            { name: 'Luang Namtha' },
            { name: 'Oudomxay' },
            { name: 'Bokeo' },
            { name: 'Houaphanh' },
            { name: 'Xiangkhouang' },
            { name: 'Vang Vieng' },
        ],
    },
    {
        name: 'Malaysia',
        cities: [
            { name: 'Johor' },
            { name: 'Kedah' },
            { name: 'Kelantan' },
            { name: 'Kuala Lumpur' },
            { name: 'Labuan' },
            { name: 'Melaka (Malacca)' },
            { name: 'Negeri Sembilan' },
            { name: 'Pahang' },
            { name: 'Penang' },
            { name: 'Perak' },
            { name: 'Perlis' },
            { name: 'Putrajaya' },
            { name: 'Sabah' },
            { name: 'Sarawak' },
            { name: 'Selangor' },
            { name: 'Terengganu' },
            { name: 'Cameron Highlands' },
        ],
    },
    {
        name: 'Myanmar',
        cities: [
            { name: 'Yangon' },
            { name: 'Mandalay' },
            { name: 'Naypyidaw' },
            { name: 'Shan State' },
            { name: 'Kachin State' },
            { name: 'Chin State' },
            { name: 'Kayah State' },
            { name: 'Kayin State' },
            { name: 'Mon State' },
            { name: 'Rakhine State' },
            { name: 'Bago Region' },
            { name: 'Magway Region' },
            { name: 'Sagaing Region' },
            { name: 'Tanintharyi Region' },
            { name: 'Ayeyarwady Region' },
            { name: 'Bagan' },
        ],
    },
    {
        name: 'Filipina',
        cities: [
            { name: 'Manila (Metro Manila)' },
            { name: 'Cebu' },
            { name: 'Davao' },
            { name: 'Benguet' },
            { name: 'Sagada (Mountain Province)' },
            { name: 'Kalinga' },
            { name: 'Ilocos' },
            { name: 'Cagayan Valley' },
            { name: 'Central Luzon' },
            { name: 'Calabarzon' },
            { name: 'Bicol Region' },
            { name: 'Western Visayas' },
            { name: 'Central Visayas' },
            { name: 'Eastern Visayas' },
            { name: 'Zamboanga Peninsula' },
            { name: 'Northern Mindanao' },
            { name: 'Davao Region' },
            { name: 'Soccsksargen' },
            { name: 'Caraga' },
            { name: 'Bangsamoro (BARMM)' },
        ],
    },
    {
        name: 'Singapura',
        cities: [
            { name: 'Singapura' }
        ],
    },
    {
        name: 'Thailand',
        cities: [
            { name: 'Bangkok' },
            { name: 'Chiang Mai' },
            { name: 'Chiang Rai' },
            { name: 'Phuket' },
            { name: 'Pattaya (Chon Buri)' },
            { name: 'Krabi' },
            { name: 'Surat Thani' },
            { name: 'Songkhla' },
            { name: 'Nakhon Ratchasima' },
            { name: 'Udon Thani' },
            { name: 'Kanchanaburi' },
            { name: 'Ayutthaya' },
        ],
    },
    {
        name: 'Vietnam',
        cities: [
            { name: 'Hanoi' },
            { name: 'Ho Chi Minh City' },
            { name: 'Da Nang' },
            { name: 'Da Lat (Lâm Đồng)' },
            { name: 'Buon Ma Thuot (Dak Lak)' },
            { name: 'Hai Phong' },
            { name: 'Can Tho' },
            { name: 'Nha Trang (Khanh Hoa)' },
            { name: 'Hue (Thua Thien Hue)' },
            { name: 'Vung Tau (Ba Ria-Vung Tau)' },
            { name: 'Quang Ninh' },
            { name: 'Son La' },
        ],
    },
    {
        name: 'Timor-Leste',
        cities: [
            { name: 'Dili' },
            { name: 'Ainaro' },
            { name: 'Ermera' },
            { name: 'Baucau' },
            { name: 'Liquiçá' },
            { name: 'Maliana (Bobonaro)' },
            { name: 'Suai (Cova Lima)' },
            { name: 'Viqueque' },
            { name: 'Oecusse' },
        ],
    },
];

export const otherRegions = [
    { name: 'Italia' },
    { name: 'Kolombia' },
    { name: 'Ethiopia' },
];
