
export const pesanHarian = [
    "Setiap biji kopi adalah janji dari sebuah pagi yang baru.",
    "Dalam heningnya secangkir kopi, kita menemukan riuh rendahnya inspirasi.",
    "Hidup itu seperti kopi, terkadang pahit, tapi itu yang membuatmu terjaga.",
    "Aroma kopi pagi adalah bisikan semesta bahwa hari ini akan indah.",
    "Jangan biarkan cangkirmu kosong, sama seperti jangan biarkan hatimu tanpa semangat.",
    "Di balik setiap tegukan, ada cerita petani, pemanggang, dan penyeduh.",
    "Kopi yang baik adalah jeda yang sempurna di tengah kesibukan dunia.",
    "Seperti latte art, keindahan seringkali muncul dari hal-hal yang tak terduga.",
    "Biarkan kopimu menjadi kuat, dan hari Seninmu menjadi singkat.",
    "Kehangatan secangkir kopi adalah pelukan dalam bentuk cair.",
    "Terkadang, jawaban terbaik datang setelah tegukan kopi pertama.",
    "Filter kopimu, bukan pikiranmu. Biarkan ide mengalir bebas.",
    "Kopi adalah bahasa universal yang menyatukan jiwa-jiwa yang lelah.",
    "Proses menyeduh kopi adalah meditasi. Nikmati setiap detiknya.",
    "Jangan hitung hari, buatlah hari-hari itu berarti, dimulai dengan secangkir kopi.",
    "Pahitnya espresso mengingatkan kita bahwa hal terbaik seringkali datang dalam dosis kecil.",
    "Semangatmu hari ini disponsori oleh kopi.",
    "Temukan duniamu dalam secangkir kopi, luas dan penuh kemungkinan.",
    "Kopi: bahan bakar legal untuk mewujudkan mimpi.",
    "Setiap cangkir adalah petualangan rasa, dari Gayo hingga Sidamo.",
    "Saat kata-kata tak cukup, biarkan kopi yang berbicara.",
    "Keajaiban dimulai saat air panas bertemu dengan bubuk kopi.",
    "Hidup terlalu singkat untuk minum kopi yang biasa-biasa saja.",
    "Secangkir kopi adalah cara alam mengatakan, 'Mari kita mulai lagi'.",
    "Jadilah seperti kopi, cukup kuat untuk meninggalkan kesan mendalam.",
    "Ide-ide besar seringkali lahir di atas uap secangkir kopi.",
    "Kopi mengajarkan kita tentang kesabaran, dari menanti seduhan hingga menikmati rasanya.",
    "Dunia terlihat lebih baik melalui dasar cangkir kopi.",
    "Biarkan aroma kopi menjadi kompas pagimu.",
    "Cinta itu seperti menyeduh kopi, butuh waktu, perhatian, dan kehangatan.",
    "Secangkir kopi di tangan, sejuta harapan di depan.",
    "Saat ragu, seduhlah kopi. Kejelasan akan mengikuti.",
    "Kopi adalah teman terbaik untuk pagi yang sunyi dan pikiran yang ramai.",
    "Setiap tetes kopi adalah puisi cair untuk jiwa.",
    "Jangan remehkan kekuatan secangkir kopi dan pikiran yang positif.",
    "Dari biji menjadi cangkir, sebuah transformasi yang menginspirasi.",
    "Kepahitan kopi adalah pengingat bahwa tidak semua yang pahit itu buruk.",
    "Seni menikmati hidup dimulai dari cara kita menikmati kopi.",
    "Kopi pagi ini adalah tombol 'reset' untuk jiwamu.",
    "Secangkir kopi, sebuah jeda untuk berterima kasih pada diri sendiri.",
    "Dalam gelapnya kopi, ada terang harapan.",
    "Jadilah alasan seseorang tersenyum hari ini, atau setidaknya buatkan mereka kopi.",
    "Kopi yang enak adalah hasil dari tangan-tangan yang penuh dedikasi.",
    "Biarkan kopimu lebih panas dari drama di sekitarmu.",
    "Seperti kopi, setiap orang punya tingkat 'kemanisan' yang berbeda.",
    "Percayalah pada keajaiban pagi dan secangkir kopi.",
    "Kopi adalah sahabat terbaik untuk buku dan hujan.",
    "Teguk kopimu, hirup semangatnya, taklukkan harimu.",
    "Keseimbangan sempurna, seperti crema di atas espresso.",
    "Di setiap cangkir, ada undangan untuk melambat dan menikmati momen."
];
