
export type City = {
    name: string;
};

export type Country = {
    name: string;
    cities: City[];
};

export type Continent = {
    name: string;
    countries: Country[];
}

export const worldRegions: Continent[] = [
    {
        name: 'Afrika',
        countries: [
            { name: 'Aljazair', cities: [{ name: 'Aljir' }, { name: 'Oran' }, { name: 'Constantine' }] },
            { name: 'Angola', cities: [{ name: 'Luanda' }, { name: 'Huambo' }, { name: 'Lobito' }] },
            { name: 'Benin', cities: [{ name: 'Porto-Novo' }, { name: 'Cotonou' }] },
            { name: 'Botswana', cities: [{ name: 'Gaborone' }, { name: 'Francistown' }] },
            { name: 'Burkina Faso', cities: [{ name: 'Ouagadougou' }, { name: 'Bobo-Dioulasso' }] },
            { name: 'Burundi', cities: [{ name: 'Gitega' }, { name: 'Bujumbura' }, { name: 'Ngozi' }, { name: 'Kayanza' }] },
            { name: 'Tanjung Verde', cities: [{ name: 'Praia' }, { name: 'Mindelo' }] },
            { name: 'Kamerun', cities: [{ name: 'Yaoundé' }, { name: 'Douala' }, { name: 'Bamenda' }] },
            { name: 'Republik Afrika Tengah', cities: [{ name: 'Bangui' }, { name: 'Bimbo' }] },
            { name: 'Chad', cities: [{ name: 'N\'Djamena' }, { name: 'Moundou' }] },
            { name: 'Komoro', cities: [{ name: 'Moroni' }] },
            { name: 'Kongo, Rep. Demokratik', cities: [{ name: 'Kinshasa' }, { name: 'Lubumbashi' }, { name: 'Mbuji-Mayi' }, { name: 'Goma' }, { name: 'Kisangani' }] },
            { name: 'Kongo, Rep.', cities: [{ name: 'Brazzaville' }, { name: 'Pointe-Noire' }] },
            { name: 'Pantai Gading', cities: [{ name: 'Yamoussoukro' }, { name: 'Abidjan' }] },
            { name: 'Jibuti', cities: [{ name: 'Djibouti' }] },
            { name: 'Mesir', cities: [{ name: 'Kairo' }, { name: 'Alexandria' }, { name: 'Giza' }] },
            { name: 'Guinea Khatulistiwa', cities: [{ name: 'Malabo' }, { name: 'Bata' }] },
            { name: 'Eritrea', cities: [{ name: 'Asmara' }] },
            { name: 'Eswatini', cities: [{ name: 'Mbabane' }, { name: 'Manzini' }] },
            { name: 'Ethiopia', cities: [{ name: 'Addis Ababa' }, { name: 'Sidamo' }, { name: 'Yirgacheffe' }, { name: 'Harrar' }, { name: 'Gondar' }, { name: 'Guji' }, { name: 'Limu' }] },
            { name: 'Gabon', cities: [{ name: 'Libreville' }, { name: 'Port-Gentil' }] },
            { name: 'Gambia', cities: [{ name: 'Banjul' }, { name: 'Serekunda' }] },
            { name: 'Ghana', cities: [{ name: 'Accra' }, { name: 'Kumasi' }] },
            { name: 'Guinea', cities: [{ name: 'Conakry' }] },
            { name: 'Guinea-Bissau', cities: [{ name: 'Bissau' }] },
            { name: 'Kenya', cities: [{ name: 'Nairobi' }, { name: 'Mombasa' }, { name: 'Nyeri' }, { name: 'Kirinyaga' }, { name: 'Kiambu' }, { name: 'Muranga' }] },
            { name: 'Lesotho', cities: [{ name: 'Maseru' }] },
            { name: 'Liberia', cities: [{ name: 'Monrovia' }] },
            { name: 'Libya', cities: [{ name: 'Tripoli' }, { name: 'Benghazi' }] },
            { name: 'Madagaskar', cities: [{ name: 'Antananarivo' }, { name: 'Toamasina' }] },
            { name: 'Malawi', cities: [{ name: 'Lilongwe' }, { name: 'Blantyre' }, { name: 'Mzuzu' }] },
            { name: 'Mali', cities: [{ name: 'Bamako' }] },
            { name: 'Mauritania', cities: [{ name: 'Nouakchott' }] },
            { name: 'Mauritius', cities: [{ name: 'Port Louis' }] },
            { name: 'Maroko', cities: [{ name: 'Rabat' }, { name: 'Casablanca' }, { name: 'Marrakesh' }] },
            { name: 'Mozambik', cities: [{ name: 'Maputo' }, { name: 'Matola' }] },
            { name: 'Namibia', cities: [{ name: 'Windhoek' }] },
            { name: 'Niger', cities: [{ name: 'Niamey' }, { name: 'Zinder' }] },
            { name: 'Nigeria', cities: [{ name: 'Abuja' }, { name: 'Lagos' }, { name: 'Kano' }, { name: 'Ibadan' }] },
            { name: 'Rwanda', cities: [{ name: 'Kigali' }, { name: 'Lake Kivu' }, { name: 'Huye' }] },
            { name: 'Sao Tome dan Principe', cities: [{ name: 'São Tomé' }] },
            { name: 'Senegal', cities: [{ name: 'Dakar' }] },
            { name: 'Seychelles', cities: [{ name: 'Victoria' }] },
            { name: 'Sierra Leone', cities: [{ name: 'Freetown' }] },
            { name: 'Somalia', cities: [{ name: 'Mogadishu' }] },
            { name: 'Afrika Selatan', cities: [{ name: 'Pretoria' }, { name: 'Cape Town' }, { name: 'Johannesburg' }] },
            { name: 'Sudan Selatan', cities: [{ name: 'Juba' }] },
            { name: 'Sudan', cities: [{ name: 'Khartoum' }] },
            { name: 'Tanzania', cities: [{ name: 'Dodoma' }, { name: 'Dar es Salaam' }, { name: 'Kilimanjaro' }, { name: 'Arusha' }, { name: 'Mbeya' }] },
            { name: 'Togo', cities: [{ name: 'Lomé' }] },
            { name: 'Tunisia', cities: [{ name: 'Tunis' }] },
            { name: 'Uganda', cities: [{ name: 'Kampala' }, { name: 'Mount Elgon' }, { name: 'Rwenzori Mountains' }] },
            { name: 'Zambia', cities: [{ name: 'Lusaka' }, { name: 'Ndola' }, { name: 'Kitwe' }] },
            { name: 'Zimbabwe', cities: [{ name: 'Harare' }, { name: 'Bulawayo' }, { name: 'Chipinge' }] },
        ]
    },
    {
        name: 'Asia',
        countries: [
            { name: 'Afganistan', cities: [{ name: 'Kabul' }] },
            { name: 'Armenia', cities: [{ name: 'Yerevan' }] },
            { name: 'Azerbaijan', cities: [{ name: 'Baku' }] },
            { name: 'Bahrain', cities: [{ name: 'Manama' }] },
            { name: 'Bangladesh', cities: [{ name: 'Dhaka' }, { name: 'Chittagong' }] },
            { name: 'Bhutan', cities: [{ name: 'Thimphu' }] },
            { name: 'Brunei', cities: [{ name: 'Bandar Seri Begawan' }] },
            { name: 'Kamboja', cities: [{ name: 'Phnom Penh' }, { name: 'Mondulkiri' }] },
            { name: 'Cina', cities: [{ name: 'Beijing' }, { name: 'Shanghai' }, { name: 'Yunnan' }, { name: 'Fujian' }, { name: 'Hainan' }] },
            { name: 'Siprus', cities: [{ name: 'Nicosia' }] },
            { name: 'Georgia', cities: [{ name: 'Tbilisi' }] },
            { name: 'India', cities: [{ name: 'New Delhi' }, { name: 'Mumbai' }, { name: 'Karnataka (Chikmagalur, Coorg)' }, { name: 'Kerala (Wayanad)' }, { name: 'Tamil Nadu (Nilgiris)' }, { name: 'Araku Valley' }] },
            { name: 'Indonesia', cities: [
                { "name": "Aceh (Gayo)" },
                { "name": "Bali (Kintamani)" },
                { "name": "Flores (Bajawa)" },
                { "name": "Jawa Barat (Preanger)" },
                { "name": "Jawa Tengah (Temanggung)" },
                { "name": "Jawa Timur (Ijen)" },
                { "name": "Lampung" },
                { "name": "Papua (Lembah Baliem)" },
                { "name": "Sulawesi (Toraja)" },
                { "name": "Sumatera Utara (Mandailing, Lintong, Sidikalang)" }
            ]},
            { name: 'Iran', cities: [{ name: 'Tehran' }] },
            { name: 'Irak', cities: [{ name: 'Baghdad' }] },
            { name: 'Israel', cities: [{ name: 'Jerusalem' }] },
            { name: 'Jepang', cities: [{ name: 'Tokyo' }, { name: 'Kyoto' }, { name: 'Osaka' }, { name: 'Okinawa' }] },
            { name: 'Yordania', cities: [{ name: 'Amman' }] },
            { name: 'Kazakhstan', cities: [{ name: 'Nur-Sultan' }] },
            { name: 'Kuwait', cities: [{ name: 'Kuwait City' }] },
            { name: 'Kirgizstan', cities: [{ name: 'Bishkek' }] },
            { name: 'Laos', cities: [{ name: 'Vientiane' }, { name: 'Bolaven Plateau' }] },
            { name: 'Lebanon', cities: [{ name: 'Beirut' }] },
            { name: 'Malaysia', cities: [{ name: 'Kuala Lumpur' }, { name: 'Cameron Highlands' }, { name: 'Sabah (Ranau)'}] },
            { name: 'Maladewa', cities: [{ name: 'Malé' }] },
            { name: 'Mongolia', cities: [{ name: 'Ulaanbaatar' }] },
            { name: 'Myanmar', cities: [{ name: 'Naypyidaw' }, { name: 'Mandalay' }, { name: 'Shan State (Ywangan)' }] },
            { name: 'Nepal', cities: [{ name: 'Kathmandu' }, { name: 'Kavre' }] },
            { name: 'Korea Utara', cities: [{ name: 'Pyongyang' }] },
            { name: 'Oman', cities: [{ name: 'Muscat' }] },
            { name: 'Pakistan', cities: [{ name: 'Islamabad' }] },
            { name: 'Palestina', cities: [{ name: 'Ramallah' }] },
            { name: 'Filipina', cities: [{ name: 'Manila' }, { name: 'Benguet' }, { name: 'Davao (Mount Apo)' }, { name: 'Sagada' }] },
            { name: 'Qatar', cities: [{ name: 'Doha' }] },
            { name: 'Arab Saudi', cities: [{ name: 'Riyadh' }, { name: 'Jizan' }] },
            { name: 'Singapura', cities: [{ name: 'Singapore' }] },
            { name: 'Korea Selatan', cities: [{ name: 'Seoul' }] },
            { name: 'Sri Lanka', cities: [{ name: 'Sri Jayawardenepura Kotte' }, { name: 'Colombo' }] },
            { name: 'Suriah', cities: [{ name: 'Damascus' }] },
            { name: 'Taiwan', cities: [{ name: 'Taipei' }, { name: 'Alishan' }] },
            { name: 'Tajikistan', cities: [{ name: 'Dushanbe' }] },
            { name: 'Thailand', cities: [{ name: 'Bangkok' }, { name: 'Chiang Mai' }, { name: 'Chiang Rai' }] },
            { name: 'Timor-Leste', cities: [{ name: 'Dili' }, { name: 'Ainaro' }] },
            { name: 'Turki', cities: [{ name: 'Ankara' }, { name: 'Istanbul' }] },
            { name: 'Turkmenistan', cities: [{ name: 'Ashgabat' }] },
            { name: 'Uni Emirat Arab', cities: [{ name: 'Abu Dhabi' }, { name: 'Dubai' }] },
            { name: 'Uzbekistan', cities: [{ name: 'Tashkent' }] },
            { name: 'Vietnam', cities: [{ name: 'Hanoi' }, { name: 'Ho Chi Minh City' }, { name: 'Da Lat (Lam Dong)' }, { name: 'Son La' }] },
            { name: 'Yaman', cities: [{ name: 'Sana\'a' }] },
        ]
    },
    {
        name: 'Eropa',
        countries: [
            { name: 'Albania', cities: [{ name: 'Tirana' }] },
            { name: 'Andorra', cities: [{ name: 'Andorra la Vella' }] },
            { name: 'Austria', cities: [{ name: 'Vienna' }] },
            { name: 'Belarus', cities: [{ name: 'Minsk' }] },
            { name: 'Belgia', cities: [{ name: 'Brussels' }] },
            { name: 'Bosnia dan Herzegovina', cities: [{ name: 'Sarajevo' }] },
            { name: 'Bulgaria', cities: [{ name: 'Sofia' }] },
            { name: 'Kroasia', cities: [{ name: 'Zagreb' }] },
            { name: 'Ceko', cities: [{ name: 'Prague' }] },
            { name: 'Denmark', cities: [{ name: 'Copenhagen' }] },
            { name: 'Estonia', cities: [{ name: 'Tallinn' }] },
            { name: 'Finlandia', cities: [{ name: 'Helsinki' }] },
            { name: 'Prancis', cities: [{ name: 'Paris' }, { name: 'Marseille' }, { name: 'Lyon' }] },
            { name: 'Jerman', cities: [{ name: 'Berlin' }, { name: 'Hamburg' }, { name: 'Munich' }] },
            { name: 'Yunani', cities: [{ name: 'Athens' }] },
            { name: 'Hungaria', cities: [{ name: 'Budapest' }] },
            { name: 'Islandia', cities: [{ name: 'Reykjavik' }] },
            { name: 'Irlandia', cities: [{ name: 'Dublin' }] },
            { name: 'Italia', cities: [{ name: 'Roma' }, { name: 'Milan' }, { name: 'Naples' }] },
            { name: 'Kosovo', cities: [{ name: 'Pristina' }] },
            { name: 'Latvia', cities: [{ name: 'Riga' }] },
            { name: 'Liechtenstein', cities: [{ name: 'Vaduz' }] },
            { name: 'Lituania', cities: [{ name: 'Vilnius' }] },
            { name: 'Luksemburg', cities: [{ name: 'Luxembourg' }] },
            { name: 'Malta', cities: [{ name: 'Valletta' }] },
            { name: 'Moldova', cities: [{ name: 'Chisinau' }] },
            { name: 'Monako', cities: [{ name: 'Monaco' }] },
            { name: 'Montenegro', cities: [{ name: 'Podgorica' }] },
            { name: 'Belanda', cities: [{ name: 'Amsterdam' }, { name: 'Rotterdam' }] },
            { name: 'Makedonia Utara', cities: [{ name: 'Skopje' }] },
            { name: 'Norwegia', cities: [{ name: 'Oslo' }] },
            { name: 'Polandia', cities: [{ name: 'Warsaw' }] },
            { name: 'Portugal', cities: [{ name: 'Lisbon' }, { name: 'Porto' }] },
            { name: 'Rumania', cities: [{ name: 'Bucharest' }] },
            { name: 'Rusia', cities: [{ name: 'Moscow' }, { name: 'Saint Petersburg' }] },
            { name: 'San Marino', cities: [{ name: 'San Marino' }] },
            { name: 'Serbia', cities: [{ name: 'Belgrade' }] },
            { name: 'Slowakia', cities: [{ name: 'Bratislava' }] },
            { name: 'Slovenia', cities: [{ name: 'Ljubljana' }] },
            { name: 'Spanyol', cities: [{ name: 'Madrid' }, { name: 'Barcelona' }] },
            { name: 'Swedia', cities: [{ name: 'Stockholm' }] },
            { name: 'Swiss', cities: [{ name: 'Bern' }, { name: 'Zürich' }, { name: 'Geneva' }] },
            { name: 'Ukraina', cities: [{ name: 'Kyiv' }] },
            { name: 'Inggris', cities: [{ name: 'London' }, { name: 'Manchester' }, { name: 'Birmingham' }] },
            { name: 'Vatikan', cities: [{ name: 'Vatican City' }] },
        ]
    },
    {
        name: 'Amerika Utara',
        countries: [
            { name: 'Antigua dan Barbuda', cities: [{ name: 'St. John\'s' }] },
            { name: 'Bahama', cities: [{ name: 'Nassau' }] },
            { name: 'Barbados', cities: [{ name: 'Bridgetown' }] },
            { name: 'Belize', cities: [{ name: 'Belmopan' }] },
            { name: 'Kanada', cities: [{ name: 'Ottawa' }, { name: 'Toronto' }, { name: 'Vancouver' }] },
            { name: 'Kosta Rika', cities: [{ name: 'San José' }, { name: 'Tarrazú' }, { name: 'West Valley' }, { name: 'Tres Rios' }] },
            { name: 'Kuba', cities: [{ name: 'Havana' }, { name: 'Sierra Maestra' }] },
            { name: 'Dominika', cities: [{ name: 'Roseau' }] },
            { name: 'Republik Dominika', cities: [{ name: 'Santo Domingo' }, { name: 'Barahona' }] },
            { name: 'El Salvador', cities: [{ name: 'San Salvador' }, { name: 'Apaneca-Ilamatepec' }, { name: 'Alotepec-Metapan' }] },
            { name: 'Grenada', cities: [{ name: 'St. George\'s' }] },
            { name: 'Guatemala', cities: [{ name: 'Guatemala City' }, { name: 'Antigua' }, { name: 'Huehuetenango' }, { name: 'Coban' }, { name: 'Atitlan' }] },
            { name: 'Haiti', cities: [{ name: 'Port-au-Prince' }] },
            { name: 'Honduras', cities: [{ name: 'Tegucigalpa' }, { name: 'Marcala' }, { name: 'Copan' }, { name: 'Agalta' }] },
            { name: 'Jamaika', cities: [{ name: 'Kingston' }, { name: 'Blue Mountains' }] },
            { name: 'Meksiko', cities: [{ name: 'Mexico City' }, { name: 'Chiapas' }, { name: 'Veracruz' }, { name: 'Oaxaca' }, { name: 'Puebla' }] },
            { name: 'Nikaragua', cities: [{ name: 'Managua' }, { name: 'Jinotega' }, { name: 'Matagalpa' }, { name: 'Nueva Segovia' }] },
            { name: 'Panama', cities: [{ name: 'Panama City' }, { name: 'Boquete' }, { name: 'Volcan' }] },
            { name: 'Saint Kitts dan Nevis', cities: [{ name: 'Basseterre' }] },
            { name: 'Saint Lucia', cities: [{ name: 'Castries' }] },
            { name: 'Saint Vincent dan Grenadines', cities: [{ name: 'Kingstown' }] },
            { name: 'Trinidad dan Tobago', cities: [{ name: 'Port of Spain' }] },
            { name: 'Amerika Serikat', cities: [{ name: 'Washington, D.C.' }, { name: 'New York' }, { name: 'Los Angeles' }, { name: 'Hawaii (Kona)' }] },
        ]
    },
    {
        name: 'Amerika Selatan',
        countries: [
            { name: 'Argentina', cities: [{ name: 'Buenos Aires' }] },
            { name: 'Bolivia', cities: [{ name: 'Sucre' }, { name: 'La Paz' }, { name: 'Caranavi' }, { name: 'Yungas' }] },
            { name: 'Brazil', cities: [{ name: 'Brasília' }, { name: 'São Paulo' }, { name: 'Rio de Janeiro' }, { name: 'Minas Gerais (Sul de Minas, Cerrado Mineiro)' }, { name: 'Bahia' }, { name: 'Espirito Santo' }] },
            { name: 'Cile', cities: [{ name: 'Santiago' }] },
            { name: 'Kolombia', cities: [{ name: 'Bogotá' }, { name: 'Medellín' }, { name: 'Huila' }, { name: 'Nariño' }, { name: 'Sierra Nevada' }, { name: 'Santander (Bucaramanga)' }] },
            { name: 'Ekuador', cities: [{ name: 'Quito' }, { name: 'Loja' }, { name: 'Galápagos' }, { name: 'Pichincha' }] },
            { name: 'Guyana', cities: [{ name: 'Georgetown' }] },
            { name: 'Paraguay', cities: [{ name: 'Asunción' }] },
            { name: 'Peru', cities: [{ name: 'Lima' }, { name: 'Cajamarca' }, { name: 'Cusco' }, { name: 'Junín' }, { name: 'Puno' }, { name: 'San Martin' }] },
            { name: 'Suriname', cities: [{ name: 'Paramaribo' }] },
            { name: 'Uruguay', cities: [{ name: 'Montevideo' }] },
            { name: 'Venezuela', cities: [{ name: 'Caracas' }] },
        ]
    },
    {
        name: 'Oseania',
        countries: [
            { name: 'Australia', cities: [{ name: 'Canberra' }, { name: 'Sydney' }, { name: 'Melbourne' }, { name: 'Northern Rivers (NSW)' }] },
            { name: 'Fiji', cities: [{ name: 'Suva' }] },
            { name: 'Kiribati', cities: [{ name: 'South Tarawa' }] },
            { name: 'Kepulauan Marshall', cities: [{ name: 'Majuro' }] },
            { name: 'Mikronesia', cities: [{ name: 'Palikir' }] },
            { name: 'Nauru', cities: [{ name: 'Yaren' }] },
            { name: 'Selandia Baru', cities: [{ name: 'Wellington' }, { name: 'Auckland' }] },
            { name: 'Palau', cities: [{ name: 'Ngerulmud' }] },
            { name: 'Papua Nugini', cities: [{ name: 'Port Moresby' }, { name: 'Eastern Highlands (Goroka)' }, { name: 'Western Highlands (Mount Hagen)' }] },
            { name: 'Samoa', cities: [{ name: 'Apia' }] },
            { name: 'Kepulauan Solomon', cities: [{ name: 'Honiara' }] },
            { name: 'Tonga', cities: [{ name: 'Nukuʻalofa' }] },
            { name: 'Tuvalu', cities: [{ name: 'Funafuti' }] },
            { name: 'Vanuatu', cities: [{ name: 'Port Vila' }] },
        ]
    }
];

// Helper untuk mendapatkan semua negara untuk dropdown
export const allCountries = worldRegions.flatMap(continent => continent.countries);

    

    